### ISSUE TITLE
Reusing name - this is going to be confusing for the users

### ISSUE THREAD

**Issue by rkujawa** [tehKaiN/AmiExtFDD#1]
Hi.

I've noticed you have used the same name that is already used by the original Roman's interface, slightly improved Zaxxon's version and also Sakura-IT/AmiExtFDD. It's already confusing when someone is talking about it, because no one ever knows which version they are referring to.

I advise either using other name, or adding some suffix to the name, or maybe create a new branch in Sakura-IT project (and include all the improvements that were added when designing this version) ? :>

**Comment by tehKaiN** [comment]
Nice! Haven't noticed that you have kinda same repo ;)

I don't like idea of having more than one stable branch, so I'd rather see it as ver. 1.1 folder on your repo.

Project would mainly consist of:

- conversion to KiCad
- some fixes regarding floppies being always detected,
- if it's possible route design to single layer with aid of TopoR lite with milling-friendly design rules

I'm more than willing to contribute with a pull request. Nonetheless I'll archive this repo as soon as this discussion is over.

**Comment by tehKaiN** [comment]
Nice! Haven't noticed that you have kinda same repo ;)

I don't like idea of having more than one stable branch, so I'd rather see it as ver. 1.1 folder on your repo.

Project would mainly consist of:

- conversion to KiCad
- some fixes regarding floppies being always detected,
- if it's possible route design to single layer with aid of TopoR lite with milling-friendly design rules.

I'm more than willing to contribute with a pull request. Nonetheless I'll archive this repo as soon as this discussion is over.

**Comment by rkujawa** [comment]
I had the same idea in the past (i.e. redoing whole thing in KiCad), but then life got in the way. Since no one else is working on this currently, I'll just send you invite to Sakura-IT organisation and grant access to AmiExtFDD repo. You are free to rearrange the contents of repository as you see fit, as long as the original version remains available. 

I'd suggest you first analyse the schematics and PCB as present in Sakura-IT/AmiExtFDD. There are some minor improvements compared to Roman's original version (these improvements were done by Roman himself and @jarob10, so maybe they already fix the problem you are talking about).

**Comment by rkujawa** [comment]
You should have received invite by now.

**Comment by tehKaiN** [comment]
I've got nothing, plz resend because I had wrong mail in profile.

**Comment by rkujawa** [comment]
Resent. You can also visit https://github.com/Sakura-IT to accept the invitation.

**Comment by tehKaiN** [comment]
Done. I'll close and archive this repo then.
